const rows=["82......9...","..7.........",".9....1.....","6...8...3...","....53..14..",".......2.8..","...8..6..5.4",".....7.3....","....1..5....","....9.......","......4...3.","....7....69."];
const solutionRows=["824175369...","157396482...","396428175...","619782543916","472653891472","538941726853","245839617524","981567234189","763214958367","...396175248","...128469735","...475382691"];
const all=new Set([1,2,3,4,5,6,7,8,9]),units=[];
for(const [grid,ro,co] of [["G1",0,0],["G2",3,3]]){for(let i=0;i<9;i++){units.push([grid+" row "+(i+1),Array.from({length:9},(_,j)=>(ro+i)*12+co+j)]);units.push([grid+" column "+(i+1),Array.from({length:9},(_,j)=>(ro+j)*12+co+i)]);}for(let br=0;br<3;br++)for(let bc=0;bc<3;bc++)units.push([grid+" box "+(br+1)+","+(bc+1),Array.from({length:9},(_,n)=>(ro+br*3+Math.floor(n/3))*12+co+bc*3+n%3)]);}
const active=[...new Set(units.flatMap(([,u])=>u))],byCell=Object.fromEntries(active.map(c=>[c,units.filter(([,u])=>u.includes(c)).map(([,u])=>u)])),peers=Object.fromEntries(active.map(c=>[c,new Set(byCell[c].flat().filter(x=>x!==c))]));
const inGrid=(r,c)=>(r<9&&c<9)||(r>=3&&c>=3);
function drawBoard(target,values){for(let r=0;r<12;r++)for(let c=0;c<12;c++){const a=r<9&&c<9,b=r>=3&&c>=3,cell=document.createElement("div");cell.className="cell";cell.style.gridColumnStart=c+1;cell.style.gridRowStart=r+1;cell.dataset.a=a;cell.dataset.b=b;if(!a&&!b)cell.classList.add("empty");if(a&&b)cell.classList.add("shared");if((a||b)&&!inGrid(r-1,c))cell.classList.add("edge-t");if((a||b)&&!inGrid(r+1,c))cell.classList.add("edge-b");if((a||b)&&!inGrid(r,c-1))cell.classList.add("edge-l");if((a||b)&&!inGrid(r,c+1))cell.classList.add("edge-r");if((a&&[2,5,8].includes(c))||(b&&[5,8,11].includes(c)))cell.classList.add("thick-r");if((a&&[2,5,8].includes(r))||(b&&[5,8,11].includes(r)))cell.classList.add("thick-b");cell.textContent=values[r][c]==="."?"":values[r][c];target.append(cell);}}
function coord(cell){const [r,c]=[Math.floor(cell/12),cell%12],out=[];if(r<9&&c<9)out.push("G1 R"+(r+1)+"C"+(c+1));if(r>=3&&c>=3)out.push("G2 R"+(r-2)+"C"+(c-2));return out.join(" / ");}
function deriveSteps(source){const v=Array(144).fill(0);source.forEach((row,r)=>[...row].forEach((x,c)=>{if(x!==".")v[r*12+c]=+x;}));const candidates=c=>new Set([...all].filter(n=>![...peers[c]].some(p=>v[p]===n))),steps=[];while(true){let move;for(const [label,u] of units){const blanks=u.filter(c=>!v[c]),miss=[...all].filter(n=>!u.some(c=>v[c]===n));if(blanks.length===1&&miss.length===1){move=["Full House",blanks[0],miss[0],label];break;}}if(!move)for(const c of active)if(!v[c]&&candidates(c).size===1){move=["Naked Single",c,[...candidates(c)][0],""];break;}if(!move)for(const [label,u] of units){for(const n of all){if(u.some(c=>v[c]===n))continue;const spots=u.filter(c=>!v[c]&&candidates(c).has(n));if(spots.length===1){move=["Hidden Single",spots[0],n,label];break;}}if(move)break;}if(!move)break;const [kind,cell,value,label]=move;v[cell]=value;steps.push([kind,coord(cell)+" = "+value+"."+(label?" Only place in "+label+".":""),cell,value]);}return steps;}
const steps=deriveSteps(rows);drawBoard(document.querySelector("#board"),rows);drawBoard(document.querySelector("#solutionBoard"),solutionRows);
const guideButton=document.querySelector("#showGuide");guideButton.onclick=()=>{const guide=document.querySelector("#guide"),hidden=guide.classList.toggle("hidden");guideButton.textContent=hidden?"Show teaching guide":"Hide teaching guide";guideButton.setAttribute("aria-expanded",String(!hidden));};
document.querySelectorAll(".grid-button").forEach(button=>button.onclick=()=>{const selected=button.dataset.grid,already=button.getAttribute("aria-pressed")==="true";document.querySelectorAll(".grid-button").forEach(b=>b.setAttribute("aria-pressed","false"));document.querySelectorAll("#board .cell").forEach(cell=>cell.classList.remove("grid-a","grid-b"));if(!already){document.querySelectorAll("#board .cell[data-"+selected+"=\"true\"]").forEach(cell=>cell.classList.add("grid-"+selected));button.setAttribute("aria-pressed","true");}});
let stepIndex=0;const count=document.querySelector("#stepCount"),technique=document.querySelector("#stepTechnique"),reasoning=document.querySelector("#stepReasoning"),previous=document.querySelector("#previousStep"),next=document.querySelector("#nextStep");function renderStep(){const [kind,text]=steps[stepIndex];count.textContent="STEP "+(stepIndex+1)+" OF "+steps.length;technique.textContent=kind;reasoning.textContent=text;previous.disabled=stepIndex===0;next.disabled=stepIndex===steps.length-1;}previous.onclick=()=>{stepIndex--;renderStep();};next.onclick=()=>{stepIndex++;renderStep();};renderStep();
let mode="human";const puzzleBoard=document.querySelector("#board");
function redraw(){const values=Array(144).fill(0);rows.forEach((row,r)=>[...row].forEach((x,c)=>{if(x!==".")values[r*12+c]=+x;}));if(mode==="solver")steps.slice(0,stepIndex+1).forEach(s=>values[s[2]]=s[3]);puzzleBoard.innerHTML="";const view=Array.from({length:12},(_,r)=>Array.from({length:12},(_,c)=>values[r*12+c]||".").join(""));drawBoard(puzzleBoard,view);puzzleBoard.querySelectorAll(".cell").forEach(cell=>{if(!cell.classList.contains("empty")&&!cell.textContent){cell.innerHTML="<span class=\"snyder\">123456789</span>";if(mode==="human"){cell.contentEditable="true";cell.onclick=()=>{if(cell.querySelector(".snyder"))cell.textContent="";};cell.oninput=()=>{cell.textContent=cell.textContent.replace(/[^1-9]/g,"").slice(-1);};}});}
function update(){renderStep();redraw();}previous.onclick=()=>{stepIndex--;update();};next.onclick=()=>{stepIndex++;update();};document.querySelectorAll(".mode-button").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".mode-button").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));document.querySelector("#modeStatus").textContent=mode==="human"?"Snyder candidates":"Step "+(stepIndex+1)+" on board";if(mode==="solver"){document.querySelector("#guide").classList.remove("hidden");guideButton.textContent="Hide teaching guide";}redraw();});redraw();
