const rows=["3.......4...","....9.......","...51..3....",".48.........","......57...9","..7.3..62..7","..6..7......","..........83","...34.....2.","...2.......4","....6.8...1.",".........5.."];
const solutionRows=["395768124...","164293857...","872514639...","248675391248","639421578369","517839462157","956187243695","483952716483","721346985721","...213659874","...564837912","...798124536"];
const steps=[
['Naked single','G2 R8C9 = 2. Its candidate list contains only 2.'],['Hidden single','G1 R2C6 = 3. It is the only place for 3 in G1 row 2.'],['Hidden single','G1 R1C5 = 6. It is the only place for 6 in G1 column 5.'],['Hidden single','G1 R4C5 / G2 R1C2 = 7. It is the only place for 7 in G1 column 5.'],['Hidden single','G1 R6C7 / G2 R3C4 = 4. It is the only place for 4 in G1 box 2,3.'],['Naked single','G2 R3C8 = 5.'],['Hidden single','G1 R4C6 / G2 R1C3 = 5. Only place for 5 in G1 box 2,2.'],['Hidden single','G1 R4C1 = 2. Only place for 2 in G1 row 4.'],['Hidden single','G1 R4C4 / G2 R1C1 = 6. Only place for 6 in G1 row 4.'],['Hidden single','G1 R5C9 / G2 R2C6 = 8. Only place for 8 in G1 box 2,3.'],['Naked single','G1 R5C5 / G2 R2C2 = 2.'],['Naked single','G1 R8C5 / G2 R5C2 = 5.'],['Naked single','G1 R7C5 / G2 R4C2 = 8.'],['Hidden single','G1 R8C6 / G2 R5C3 = 2. Only place for 2 in G1 box 3,2.'],['Naked single','G1 R1C6 = 8.'],['Naked single','G1 R3C6 = 4.'],['Naked single','G1 R5C6 / G2 R2C3 = 1.'],['Naked single','G1 R5C4 / G2 R2C1 = 4.'],['Naked single','G1 R6C6 / G2 R3C3 = 9.'],['Naked single','G1 R6C4 / G2 R3C1 = 8.'],['Naked single','G2 R3C7 = 1.'],['Naked single','G2 R1C9 = 8.'],['Naked single','G1 R9C6 / G2 R6C3 = 6.'],['Naked single','G2 R9C9 = 6.'],['Hidden single','G1 R9C8 / G2 R6C5 = 8. Only place for 8 in G1 box 3,3.'],['Hidden single','G2 R1C7 = 2. Only place for 2 in G2 row 1.'],['Hidden single','G2 R1C8 = 4. Only place for 4 in G2 row 1.'],['Hidden single','G2 R9C3 = 8. Only place for 8 in G2 row 9.'],['Naked single','G2 R7C3 = 3.'],['Naked single','G2 R8C3 = 4.'],['Hidden single','G2 R7C7 = 8. Only place for 8 in G2 row 7.'],['Hidden single','G2 R8C1 = 5. Only place for 5 in G2 column 1.'],['Hidden single','G2 R9C1 = 7. Only place for 7 in G2 column 1.'],['Hidden single','G2 R9C6 = 4. Only place for 4 in G2 column 6.'],['Hidden single','G2 R7C8 = 7. Only place for 7 in G2 column 8.'],['Hidden single','G2 R8C6 = 7. Only place for 7 in G2 row 8.']
];
const inGrid=(r,c)=>(r<9&&c<9)||(r>=3&&c>=3);
function drawBoard(target,values){for(let r=0;r<12;r++)for(let c=0;c<12;c++){const a=r<9&&c<9,b=r>=3&&c>=3,cell=document.createElement('div');cell.className='cell';cell.style.gridColumnStart=String(c+1);cell.style.gridRowStart=String(r+1);cell.dataset.a=a;cell.dataset.b=b;if(!a&&!b)cell.classList.add('empty');if(a&&b)cell.classList.add('shared');if((a||b)&&!inGrid(r-1,c))cell.classList.add('edge-t');if((a||b)&&!inGrid(r+1,c))cell.classList.add('edge-b');if((a||b)&&!inGrid(r,c-1))cell.classList.add('edge-l');if((a||b)&&!inGrid(r,c+1))cell.classList.add('edge-r');if((a&&[2,5,8].includes(c))||(b&&[5,8,11].includes(c)))cell.classList.add('thick-r');if((a&&[2,5,8].includes(r))||(b&&[5,8,11].includes(r)))cell.classList.add('thick-b');cell.textContent=values[r][c]==='.'?'':values[r][c];target.append(cell);}}
drawBoard(document.querySelector('#board'),rows);drawBoard(document.querySelector('#solutionBoard'),solutionRows);
const guideButton=document.querySelector('#showGuide');guideButton.onclick=()=>{const guide=document.querySelector('#guide'),hidden=guide.classList.toggle('hidden');guideButton.textContent=hidden?'Show teaching guide':'Hide teaching guide';guideButton.setAttribute('aria-expanded',String(!hidden));};
document.querySelectorAll('.grid-button').forEach(button=>button.onclick=()=>{const selected=button.dataset.grid,already=button.getAttribute('aria-pressed')==='true';document.querySelectorAll('.grid-button').forEach(b=>b.setAttribute('aria-pressed','false'));document.querySelectorAll('#board .cell').forEach(cell=>cell.classList.remove('grid-a','grid-b'));if(!already){document.querySelectorAll(`#board .cell[data-${selected}="true"]`).forEach(cell=>cell.classList.add(`grid-${selected}`));button.setAttribute('aria-pressed','true');}});
let stepIndex=0;const count=document.querySelector('#stepCount'),technique=document.querySelector('#stepTechnique'),reasoning=document.querySelector('#stepReasoning'),previous=document.querySelector('#previousStep'),next=document.querySelector('#nextStep');
function renderStep(){const [kind,text]=steps[stepIndex];count.textContent=`STEP ${stepIndex+1} OF ${steps.length}`;technique.textContent=kind;reasoning.textContent=text;previous.disabled=stepIndex===0;next.disabled=stepIndex===steps.length-1;}
previous.onclick=()=>{stepIndex--;renderStep();};next.onclick=()=>{stepIndex++;renderStep();};renderStep();
